// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AccessTokenResponse struct {
	Token            string `json:"token"`
	ExpiresAt        int    `json:"expires_at"`
	RefreshToken     string `json:"refresh_token"`
	RefreshExpiresAt int    `json:"refresh_expires_at"`
}

type AccesstokenRequest struct {
	AuthCode string `json:"auth_code"`
}

type AuthCodeResponse struct {
	Code      string `json:"code"`
	ExpiresAt int    `json:"expires_at"`
}

type AuthorizeRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type CreateEmployeeRequest struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Employee struct {
	ID        string    `json:"id"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type FilterCriterias struct {
	ID    *string `json:"id"`
	Name  *string `json:"name"`
	Email *string `json:"email"`
}

type MeResponse struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PageCriterias struct {
	Page *int    `json:"page"`
	Size *int    `json:"size"`
	Sort *string `json:"sort"`
}

type RefreshtokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UpdateEmployeeRequest struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
